# --- RABBITMQ (Required for Receiver to start) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

---
# --- RECEIVER DATABASE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-db
spec:
  selector:
    matchLabels:
      app: receiver-db
  template:
    metadata:
      labels:
        app: receiver-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: receivers_db
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-db
spec:
  selector:
    app: receiver-db
  ports:
    - port: 5432
      targetPort: 5432

---
# --- RECEIVER SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-service
  template:
    metadata:
      labels:
        app: receiver-service
    spec:
      containers:
      - name: receiver
        image: rahuly13/receiver-service:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgres://user:postgres@receiver-db:5432/receivers_db"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: receiver-service
  ports:
    - port: 80
      targetPort: 3000

---
# --- INGRESS (The Public Entrance) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /receiver(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: receiver-service
            port:
              number: 80