apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiver-service
  template:
    metadata:
      labels:
        app: receiver-service
    spec:
      containers:
      - name: receiver
        image: rahuly13/receiver-service:latest
        env:
        - name: DATABASE_URL
          value: "postgres://user:postgres@receiver-db:5432/receivers_db"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: receiver-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000