# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: banking-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     # This allows larger headers if you use JWTs later
#     nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http: # Removed the 'host: banking.local' line to allow Public IP access
#       paths:
#       - path: /receiver(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: receiver-service
#             port:
#               number: 3000
#       - path: /notifications(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: notification-service
#             port:
#               number: 3002