apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: receiver-service-monitor
  namespace: monitoring
  labels:
    # This MUST match the release name you used in the ArgoCD Monitoring App
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: receiver-service # Matches the Service label
  namespaceSelector:
    matchNames:
      - default # The namespace where your app lives
  endpoints:
  - port: http
    path: /metrics
    interval: 15s